# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [4]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([45,76,99,105])
arr1

array([ 45,  76,  99, 105])

In [5]:
# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[34,56,22],[63,88,53]])
arr2

array([[34, 56, 22],
       [63, 88, 53]])

In [7]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape: ",arr1.shape)
print("Number of dimensions: ",arr1.ndim)
print("Datatype: ",arr1.dtype)
print("Size: ",arr1.size)
print("Type: ",type(arr1))

Shape:  (4,)
Number of dimensions:  1
Datatype:  int32
Size:  4
Type:  <class 'numpy.ndarray'>


In [8]:
# Attributes of 2-dimensional array
print("Shape: ",arr2.shape)
print("Number of dimensions: ",arr2.ndim)
print("Datatype: ",arr2.dtype)
print("Size: ",arr2.size)
print("Type: ",type(arr2))

Shape:  (2, 3)
Number of dimensions:  2
Datatype:  int32
Size:  6
Type:  <class 'numpy.ndarray'>


In [11]:
# Create an array of shape (5, 5) with only ones
np.ones((5,5)).astype(int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [12]:
# Create an array of shape (3, 3, 5) with only zeros
np.zeros((3,3,5)).astype(int)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [13]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(10, size=(7,2))
random_array

array([[0, 6],
       [7, 3],
       [9, 7],
       [8, 2],
       [9, 1],
       [1, 4],
       [2, 7]])

In [19]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
r_a = np.random.random((3,5))
r_a

array([[0.27982736, 0.29875953, 0.77704547, 0.90166192, 0.05135924],
       [0.96028952, 0.33617548, 0.66571044, 0.8545416 , 0.86422864],
       [0.56351153, 0.52098416, 0.05859853, 0.94453586, 0.47507467]])

In [21]:
# Create an array of normally distributed random numbers
np.random.randn(int(input()),int(input()))

5
3


array([[ 0.82833563,  0.39700257,  0.24658483],
       [ 0.15698617, -0.98489947, -0.82798851],
       [ 1.10980084, -0.88449552,  0.70906218],
       [ 0.48826243,  1.97034337, -1.38981939],
       [-0.06162069, -0.96662128,  1.38336935]])

In [24]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
np.random.randint(10, size=(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [26]:
# Copy the code from the cell above and run it again
np.random.seed(42)
ran=np.random.randint(10, size=(4,6))
ran

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [29]:
# Find the 0'th index of the latest array you created
ran[0,0]

6

In [28]:
# Get the first 2 rows of latest array you created
ran[0:2]

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
ran[:2,:2]

array([[6, 3],
       [2, 6]])

In [37]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
array1 = np.random.randint(10, size=(3,5))
array2 = np.ones((3,5)).astype(int)
print(array1)
print("\n")
print(array2)

[[7 3 1 5 5]
 [9 3 5 1 9]
 [1 9 3 7 6]]


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [40]:
# Add the two arrays together
sum = array1 + array2
sum

array([[ 8,  4,  2,  6,  6],
       [10,  4,  6,  2, 10],
       [ 2, 10,  4,  8,  7]])

In [41]:
# Create another array of ones of shape (5, 3)
arr = np.ones((5,3))

In [42]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
arr + sum

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [46]:
# Do the same operation you just did but this time with a transpose on one array
a = arr + sum.T
a.astype(int)

array([[ 9, 11,  3],
       [ 5,  5, 11],
       [ 3,  7,  5],
       [ 7,  3,  9],
       [ 7, 11,  8]])

In [49]:
# Take the latest array to the power of 2 using the python way
b = a**2
b.astype(int)

array([[ 81, 121,   9],
       [ 25,  25, 121],
       [  9,  49,  25],
       [ 49,   9,  81],
       [ 49, 121,  64]])

In [51]:
# Do the same thing with numpy way
np.square(a).astype(int)

array([[ 81, 121,   9],
       [ 25,  25, 121],
       [  9,  49,  25],
       [ 49,   9,  81],
       [ 49, 121,  64]])

In [52]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print("Mean: ",np.mean(b))
print("Min: ",np.min(b))
print("MAx: ",np.max(b))
print("Standard deviation: ",np.std(b))
print("Variance: ",np.var(b))

Mean:  55.86666666666667
Min:  9.0
MAx:  121.0
Standard deviation:  39.703680210053854
Variance:  1576.3822222222218


In [57]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
a1 = np.random.randint(10, size=(3,3))
a2 = np.random.randint(10,size=(3,2))
print(a1)
print("\n")
print(a2)

[[0 4 9]
 [6 6 8]
 [9 9 2]]


[[6 0]
 [3 3]
 [4 6]]


In [58]:
# Perform a dot product on the two newest arrays you created
np.dot(a1, a2)

array([[48, 66],
       [86, 66],
       [89, 39]])

In [59]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
m = np.random.randint(10,size=(4,3))
n = np.random.randint(10,size=(4,3))
print(m)
print("\n")
print(n)

[[6 3 6]
 [2 5 1]
 [9 8 4]
 [5 3 9]]


[[6 8 6]
 [0 0 8]
 [8 3 8]
 [2 6 5]]


In [60]:
# Perform a hadamard product on the two newest arrays you created
m * n

array([[36, 24, 36],
       [ 0,  0,  8],
       [72, 24, 32],
       [10, 18, 45]])

In [61]:
# Perform a dot product on the two newest arrays you created # Error anticipated
np.dot(m, n)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [62]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both
np.dot(m, n.T).astype(int)

array([[ 96,  48, 105,  60],
       [ 58,   8,  39,  39],
       [142,  32, 128,  86],
       [108,  72, 121,  73]])

In [71]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
p = np.random.randint(10, size=(3,4))
q = np.random.randint(10,size=(3,4))
print(p)
print("\n")
print(q)

[[2 8 2 8]
 [1 1 1 5]
 [2 8 3 0]]


[[3 0 4 3]
 [7 7 6 2]
 [0 0 2 5]]


In [72]:
# Compare the two arrays with '>', '<=' and '==' 
print(p>q)
print(p<=q)
print(p==q)

[[False  True False  True]
 [False False False  True]
 [ True  True  True False]]
[[ True False  True False]
 [ True  True  True False]
 [False False False  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


In [73]:
# Sort one of the arrays you just created in ascending order
np.sort(p)

array([[2, 2, 8, 8],
       [1, 1, 1, 5],
       [0, 2, 3, 8]])

In [74]:
# Sort the indexes of one of the arrays you just created
np.argsort(p)

array([[0, 2, 1, 3],
       [0, 1, 2, 3],
       [3, 0, 2, 1]], dtype=int64)

In [76]:
# Find the index with the maximum value in one of the arrays you've created
np.amax(p)

8

In [78]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.arange(start=1, stop=100, step=10)

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [80]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(p, axis=1)

array([1, 3, 1], dtype=int64)

In [81]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(p, axis=0)

array([1, 1, 1, 2], dtype=int64)